// src/data/products.js
export const dummyProducts = [
    {
        id: 1,
        name: "Gradient Graphic T-shirt",
        price: 25,
        discount: 20, // means 20% off
        color: "Pink",
        size: "M",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+1",
    },
    {
        id: 2,
        name: "Polo with Tipping Details",
        price: 30,
        discount: 0,
        color: "White",
        size: "L",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+2",
    },
    {
        id: 3,
        name: "Black Striped T-shirt",
        price: 15,
        discount: 10,
        color: "Black",
        size: "S",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+3",
    },
    {
        id: 4,
        name: "Skinny Fit Jeans",
        price: 40,
        discount: 0,
        color: "Blue",
        size: "M",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+4",
    },
    {
        id: 5,
        name: "Checkered Shirt",
        price: 35,
        discount: 15,
        color: "Red",
        size: "XL",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+5",
    },
    {
        id: 6,
        name: "Sleeve Striped T-shirt",
        price: 18,
        discount: 5,
        color: "Gray",
        size: "M",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+6",
    },
    {
        id: 7,
        name: "Vertical Striped Shirt",
        price: 22,
        discount: 30,
        color: "Green",
        size: "S",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+7",
    },
    {
        id: 8,
        name: "Orange Graphic T-shirt",
        price: 14,
        discount: 0,
        color: "Orange",
        size: "M",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+8",
    },
    {
        id: 9,
        name: "Loose Fit Bermuda Shorts",
        price: 20,
        discount: 25,
        color: "Navy",
        size: "L",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+9",
    },
    {
        id: 10,
        name: "Casual Hoodie",
        price: 50,
        discount: 10,
        color: "Black",
        size: "XL",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+10",
    },
    {
        id: 1,
        name: "Gradient Graphic T-shirt",
        price: 25,
        discount: 20, // means 20% off
        color: "Pink",
        size: "M",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+1",
    },
    {
        id: 2,
        name: "Polo with Tipping Details",
        price: 30,
        discount: 0,
        color: "White",
        size: "L",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+2",
    },
    {
        id: 3,
        name: "Black Striped T-shirt",
        price: 15,
        discount: 10,
        color: "Black",
        size: "S",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+3",
    },
    {
        id: 4,
        name: "Skinny Fit Jeans",
        price: 40,
        discount: 0,
        color: "Blue",
        size: "M",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+4",
    },
    {
        id: 5,
        name: "Checkered Shirt",
        price: 35,
        discount: 15,
        color: "Red",
        size: "XL",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+5",
    },
    {
        id: 6,
        name: "Sleeve Striped T-shirt",
        price: 18,
        discount: 5,
        color: "Gray",
        size: "M",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+6",
    },
    {
        id: 7,
        name: "Vertical Striped Shirt",
        price: 22,
        discount: 30,
        color: "Green",
        size: "S",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+7",
    },
    {
        id: 8,
        name: "Orange Graphic T-shirt",
        price: 14,
        discount: 0,
        color: "Orange",
        size: "M",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+8",
    },
    {
        id: 9,
        name: "Loose Fit Bermuda Shorts",
        price: 20,
        discount: 25,
        color: "Navy",
        size: "L",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+9",
    },
    {
        id: 10,
        name: "Casual Hoodie",
        price: 50,
        discount: 10,
        color: "Black",
        size: "XL",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+10",
    },
    // Add more dummy products as needed...
    {
        id: 1,
        name: "Gradient Graphic T-shirt",
        price: 25,
        discount: 20, // means 20% off
        color: "Pink",
        size: "M",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+1",
    },
    {
        id: 2,
        name: "Polo with Tipping Details",
        price: 30,
        discount: 0,
        color: "White",
        size: "L",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+2",
    },
    {
        id: 3,
        name: "Black Striped T-shirt",
        price: 15,
        discount: 10,
        color: "Black",
        size: "S",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+3",
    },
    {
        id: 4,
        name: "Skinny Fit Jeans",
        price: 40,
        discount: 0,
        color: "Blue",
        size: "M",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+4",
    },
    {
        id: 5,
        name: "Checkered Shirt",
        price: 35,
        discount: 15,
        color: "Red",
        size: "XL",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+5",
    },
    {
        id: 6,
        name: "Sleeve Striped T-shirt",
        price: 18,
        discount: 5,
        color: "Gray",
        size: "M",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+6",
    },
    {
        id: 7,
        name: "Vertical Striped Shirt",
        price: 22,
        discount: 30,
        color: "Green",
        size: "S",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+7",
    },
    {
        id: 8,
        name: "Orange Graphic T-shirt",
        price: 14,
        discount: 0,
        color: "Orange",
        size: "M",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+8",
    },
    {
        id: 9,
        name: "Loose Fit Bermuda Shorts",
        price: 20,
        discount: 25,
        color: "Navy",
        size: "L",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+9",
    },
    {
        id: 10,
        name: "Casual Hoodie",
        price: 50,
        discount: 10,
        color: "Black",
        size: "XL",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+10",
    },
    {
        id: 1,
        name: "Gradient Graphic T-shirt",
        price: 25,
        discount: 20, // means 20% off
        color: "Pink",
        size: "M",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+1",
    },
    {
        id: 2,
        name: "Polo with Tipping Details",
        price: 30,
        discount: 0,
        color: "White",
        size: "L",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+2",
    },
    {
        id: 3,
        name: "Black Striped T-shirt",
        price: 15,
        discount: 10,
        color: "Black",
        size: "S",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+3",
    },
    {
        id: 4,
        name: "Skinny Fit Jeans",
        price: 40,
        discount: 0,
        color: "Blue",
        size: "M",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+4",
    },
    {
        id: 5,
        name: "Checkered Shirt",
        price: 35,
        discount: 15,
        color: "Red",
        size: "XL",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+5",
    },
    {
        id: 6,
        name: "Sleeve Striped T-shirt",
        price: 18,
        discount: 5,
        color: "Gray",
        size: "M",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+6",
    },
    {
        id: 7,
        name: "Vertical Striped Shirt",
        price: 22,
        discount: 30,
        color: "Green",
        size: "S",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+7",
    },
    {
        id: 8,
        name: "Orange Graphic T-shirt",
        price: 14,
        discount: 0,
        color: "Orange",
        size: "M",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+8",
    },
    {
        id: 9,
        name: "Loose Fit Bermuda Shorts",
        price: 20,
        discount: 25,
        color: "Navy",
        size: "L",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+9",
    },
    {
        id: 10,
        name: "Casual Hoodie",
        price: 50,
        discount: 10,
        color: "Black",
        size: "XL",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+10",
    },
    // Add more dummy products as needed...
    {
        id: 1,
        name: "Gradient Graphic T-shirt",
        price: 25,
        discount: 20, // means 20% off
        color: "Pink",
        size: "M",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+1",
    },
    {
        id: 2,
        name: "Polo with Tipping Details",
        price: 30,
        discount: 0,
        color: "White",
        size: "L",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+2",
    },
    {
        id: 3,
        name: "Black Striped T-shirt",
        price: 15,
        discount: 10,
        color: "Black",
        size: "S",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+3",
    },
    {
        id: 4,
        name: "Skinny Fit Jeans",
        price: 40,
        discount: 0,
        color: "Blue",
        size: "M",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+4",
    },
    {
        id: 5,
        name: "Checkered Shirt",
        price: 35,
        discount: 15,
        color: "Red",
        size: "XL",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+5",
    },
    {
        id: 6,
        name: "Sleeve Striped T-shirt",
        price: 18,
        discount: 5,
        color: "Gray",
        size: "M",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+6",
    },
    {
        id: 7,
        name: "Vertical Striped Shirt",
        price: 22,
        discount: 30,
        color: "Green",
        size: "S",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+7",
    },
    {
        id: 8,
        name: "Orange Graphic T-shirt",
        price: 14,
        discount: 0,
        color: "Orange",
        size: "M",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+8",
    },
    {
        id: 9,
        name: "Loose Fit Bermuda Shorts",
        price: 20,
        discount: 25,
        color: "Navy",
        size: "L",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+9",
    },
    {
        id: 10,
        name: "Casual Hoodie",
        price: 50,
        discount: 10,
        color: "Black",
        size: "XL",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+10",
    },
    {
        id: 1,
        name: "Gradient Graphic T-shirt",
        price: 25,
        discount: 20, // means 20% off
        color: "Pink",
        size: "M",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+1",
    },
    {
        id: 2,
        name: "Polo with Tipping Details",
        price: 30,
        discount: 0,
        color: "White",
        size: "L",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+2",
    },
    {
        id: 3,
        name: "Black Striped T-shirt",
        price: 15,
        discount: 10,
        color: "Black",
        size: "S",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+3",
    },
    {
        id: 4,
        name: "Skinny Fit Jeans",
        price: 40,
        discount: 0,
        color: "Blue",
        size: "M",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+4",
    },
    {
        id: 5,
        name: "Checkered Shirt",
        price: 35,
        discount: 15,
        color: "Red",
        size: "XL",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+5",
    },
    {
        id: 6,
        name: "Sleeve Striped T-shirt",
        price: 18,
        discount: 5,
        color: "Gray",
        size: "M",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+6",
    },
    {
        id: 7,
        name: "Vertical Striped Shirt",
        price: 22,
        discount: 30,
        color: "Green",
        size: "S",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+7",
    },
    {
        id: 8,
        name: "Orange Graphic T-shirt",
        price: 14,
        discount: 0,
        color: "Orange",
        size: "M",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+8",
    },
    {
        id: 9,
        name: "Loose Fit Bermuda Shorts",
        price: 20,
        discount: 25,
        color: "Navy",
        size: "L",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+9",
    },
    {
        id: 10,
        name: "Casual Hoodie",
        price: 50,
        discount: 10,
        color: "Black",
        size: "XL",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+10",
    },
    // Add more dummy products as needed...
    {
        id: 1,
        name: "Gradient Graphic T-shirt",
        price: 25,
        discount: 20, // means 20% off
        color: "Pink",
        size: "M",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+1",
    },
    {
        id: 2,
        name: "Polo with Tipping Details",
        price: 30,
        discount: 0,
        color: "White",
        size: "L",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+2",
    },
    {
        id: 3,
        name: "Black Striped T-shirt",
        price: 15,
        discount: 10,
        color: "Black",
        size: "S",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+3",
    },
    {
        id: 4,
        name: "Skinny Fit Jeans",
        price: 40,
        discount: 0,
        color: "Blue",
        size: "M",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+4",
    },
    {
        id: 5,
        name: "Checkered Shirt",
        price: 35,
        discount: 15,
        color: "Red",
        size: "XL",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+5",
    },
    {
        id: 6,
        name: "Sleeve Striped T-shirt",
        price: 18,
        discount: 5,
        color: "Gray",
        size: "M",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+6",
    },
    {
        id: 7,
        name: "Vertical Striped Shirt",
        price: 22,
        discount: 30,
        color: "Green",
        size: "S",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+7",
    },
    {
        id: 8,
        name: "Orange Graphic T-shirt",
        price: 14,
        discount: 0,
        color: "Orange",
        size: "M",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+8",
    },
    {
        id: 9,
        name: "Loose Fit Bermuda Shorts",
        price: 20,
        discount: 25,
        color: "Navy",
        size: "L",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+9",
    },
    {
        id: 10,
        name: "Casual Hoodie",
        price: 50,
        discount: 10,
        color: "Black",
        size: "XL",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+10",
    },
    {
        id: 1,
        name: "Gradient Graphic T-shirt",
        price: 25,
        discount: 20, // means 20% off
        color: "Pink",
        size: "M",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+1",
    },
    {
        id: 2,
        name: "Polo with Tipping Details",
        price: 30,
        discount: 0,
        color: "White",
        size: "L",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+2",
    },
    {
        id: 3,
        name: "Black Striped T-shirt",
        price: 15,
        discount: 10,
        color: "Black",
        size: "S",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+3",
    },
    {
        id: 4,
        name: "Skinny Fit Jeans",
        price: 40,
        discount: 0,
        color: "Blue",
        size: "M",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+4",
    },
    {
        id: 5,
        name: "Checkered Shirt",
        price: 35,
        discount: 15,
        color: "Red",
        size: "XL",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+5",
    },
    {
        id: 6,
        name: "Sleeve Striped T-shirt",
        price: 18,
        discount: 5,
        color: "Gray",
        size: "M",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+6",
    },
    {
        id: 7,
        name: "Vertical Striped Shirt",
        price: 22,
        discount: 30,
        color: "Green",
        size: "S",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+7",
    },
    {
        id: 8,
        name: "Orange Graphic T-shirt",
        price: 14,
        discount: 0,
        color: "Orange",
        size: "M",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+8",
    },
    {
        id: 9,
        name: "Loose Fit Bermuda Shorts",
        price: 20,
        discount: 25,
        color: "Navy",
        size: "L",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+9",
    },
    {
        id: 10,
        name: "Casual Hoodie",
        price: 50,
        discount: 10,
        color: "Black",
        size: "XL",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+10",
    },
    // Add more dummy products as needed...
    {
        id: 1,
        name: "Gradient Graphic T-shirt",
        price: 25,
        discount: 20, // means 20% off
        color: "Pink",
        size: "M",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+1",
    },
    {
        id: 2,
        name: "Polo with Tipping Details",
        price: 30,
        discount: 0,
        color: "White",
        size: "L",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+2",
    },
    {
        id: 3,
        name: "Black Striped T-shirt",
        price: 15,
        discount: 10,
        color: "Black",
        size: "S",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+3",
    },
    {
        id: 4,
        name: "Skinny Fit Jeans",
        price: 40,
        discount: 0,
        color: "Blue",
        size: "M",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+4",
    },
    {
        id: 5,
        name: "Checkered Shirt",
        price: 35,
        discount: 15,
        color: "Red",
        size: "XL",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+5",
    },
    {
        id: 6,
        name: "Sleeve Striped T-shirt",
        price: 18,
        discount: 5,
        color: "Gray",
        size: "M",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+6",
    },
    {
        id: 7,
        name: "Vertical Striped Shirt",
        price: 22,
        discount: 30,
        color: "Green",
        size: "S",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+7",
    },
    {
        id: 8,
        name: "Orange Graphic T-shirt",
        price: 14,
        discount: 0,
        color: "Orange",
        size: "M",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+8",
    },
    {
        id: 9,
        name: "Loose Fit Bermuda Shorts",
        price: 20,
        discount: 25,
        color: "Navy",
        size: "L",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+9",
    },
    {
        id: 10,
        name: "Casual Hoodie",
        price: 50,
        discount: 10,
        color: "Black",
        size: "XL",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+10",
    },
    {
        id: 1,
        name: "Gradient Graphic T-shirt",
        price: 25,
        discount: 20, // means 20% off
        color: "Pink",
        size: "M",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+1",
    },
    {
        id: 2,
        name: "Polo with Tipping Details",
        price: 30,
        discount: 0,
        color: "White",
        size: "L",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+2",
    },
    {
        id: 3,
        name: "Black Striped T-shirt",
        price: 15,
        discount: 10,
        color: "Black",
        size: "S",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+3",
    },
    {
        id: 4,
        name: "Skinny Fit Jeans",
        price: 40,
        discount: 0,
        color: "Blue",
        size: "M",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+4",
    },
    {
        id: 5,
        name: "Checkered Shirt",
        price: 35,
        discount: 15,
        color: "Red",
        size: "XL",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+5",
    },
    {
        id: 6,
        name: "Sleeve Striped T-shirt",
        price: 18,
        discount: 5,
        color: "Gray",
        size: "M",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+6",
    },
    {
        id: 7,
        name: "Vertical Striped Shirt",
        price: 22,
        discount: 30,
        color: "Green",
        size: "S",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+7",
    },
    {
        id: 8,
        name: "Orange Graphic T-shirt",
        price: 14,
        discount: 0,
        color: "Orange",
        size: "M",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+8",
    },
    {
        id: 9,
        name: "Loose Fit Bermuda Shorts",
        price: 20,
        discount: 25,
        color: "Navy",
        size: "L",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+9",
    },
    {
        id: 10,
        name: "Casual Hoodie",
        price: 50,
        discount: 10,
        color: "Black",
        size: "XL",
        style: "Casual",
        image: "https://via.placeholder.com/300x300.png?text=Product+10",
    },
    // Add more dummy products as needed...
];
